esphome:
  name: adonno02
  friendly_name: adonno02

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "E5iWaGU6dYYxEkvONL+6j9mkSMaLB2NBlynj/n+B/Vk="

ota:
  - platform: esphome
    password: "353a5deebcfb0f52df19d14ebbc682e4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Adonno02 Fallback Hotspot"
    password: "EhAdmQvTWsz6"

captive_portal:
    