esphome:
  name: core-2
  friendly_name: core 2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ySSPMhwT+ZsdDWni5J27+LKqYOrMxwgSM0QJpJo2eWY="

ota:
  - platform: esphome
    password: "fb4303079d871c0d6b5cc4baf788ea26"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Core-2 Fallback Hotspot"
    password: "0ITbWFVnm6Gr"

captive_portal:
    