substitutions:
  name: esphome-8c8d46
  friendly_name: TagReader01
packages:
  adonno.tag_reader: github://adonno/tagreader/tagreader.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: tiyfEHSt/ab0kDUvvlUO0b0LafWZh5rDERvPchmd1yA=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
