substitutions:
  name: m5stack-atom-echo-a15a0c
  friendly_name: M5Stack Atom Echo 02
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 4gWSDMRja4Bfy708QzNI0cRWlT3cJ6G4ZDVd5FVL6e8=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
