substitutions:
  name: adonno01
packages:
  adonno.tag_reader: github://adonno/tagreader/tagreader.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
#  encryption:
#    key: PlYfRJepexGbdI8C7bm/BOzSJ2j2n8YNl+CmyumP5RY=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
