# Your Wi-Fi SSID and password
# OLD wifi_ssid: "CH8__________00"
# OLD wifi_password: "z__________rg"

wifi_hotspot_password: "k__________9"

#wifi2 is for all new devices - FW pfsense
# fast_connect: true/false  - true doesn't scan for networks and connects faster.
wifi2_fast_connect: false
# NONE (least power saving, Default for ESP8266)
# LIGHT (Default for ESP32)
# HIGH (most power saving)
wifi2_power_save_mode: none
# Wifi credentials wenn nur ein Netzwerk aber auch wenn zwei WiFi konfiguriert wurden!!!
wifi2_ssid: "Re_______er2"
wifi2_password: "K5Z______28"
wifi2_priority: "9"
wifi2_ssid_2: "Re_______er2"
wifi2_password_2: "K5Z______28&4428"
wifi2_priority_2: "8"
wifi2_ssid_3: "Re_______er2"
wifi2_password_3: "K5Z______28&4428"
wifi2_priority_3: "7"
wifi2_ssid_4: "Ile_______e_2"
wifi2_password_4: "Pa_______3"
wifi2_priority_4: "5"
wifi2_ssid_5: "L_____eL______on"
wifi2_password_5: "S_____A_____9"
wifi2_priority_5: "3"


# wifi2_domain: ".main.arpa"  - das funktioniert nicht 100%
# wifi2_domain: ".local"
wifi2_domain: ".main.arpa"


ap_password: "R_______9"


api_encryption_key: "tE_____________________________s5wmg="
ota_encrpytion_key: "378___________________e4579"


m5dial_mqtt_broker: 10.100.23.100
m5dial_mqtt_user: m___________t
m5dial_mqtt_password: m_________t


# name: tagreader-8c8d46
# key:  BCw+h455Fvt59/JDNr0D1aN/l+I4d7TbwD5UZ91w92Y=

# encryption_key: "ViyEyC+lpyDXtCDeh18LXv8A1FOtVeq4cL2C4UzhSJo="

esphome-8c8d46_encryption_key: "GL__________________________mMNw="

Tagreader01: "ioh__________________________bsTI="


encryption_key: "2ynA___________________E5CI="


# Your Wi-Fi SSID and password
wifi_ssid: "Re_______er2"
wifi_password: "K5Z______28"
